"""Initial migration

Revision ID: dddceb6761a9
Revises:
Create Date: 2024-10-20 21:46:08.696471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dddceb6761a9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('food_entries',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('food_name', sa.String(), nullable=False),
    # sa.Column('category', sa.String(), nullable=False),
    # sa.Column('date', sa.String(), nullable=False),
    # sa.Column('quantity', sa.String(), nullable=False),
    # sa.Column('calories', sa.String(), nullable=True),
    # sa.Column('notes', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_food_entries_id'), 'food_entries', ['id'], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # op.drop_index(op.f('ix_food_entries_id'), table_name='food_entries')
    # op.drop_table('food_entries')
    # ### end Alembic commands ###
