"""empty message

Revision ID: f506102b1f64
Revises: 67508bc19929
Create Date: 2024-12-09 00:49:15.744428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f506102b1f64'
down_revision: Union[str, None] = '67508bc19929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_userdb_id', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('ix_userdb_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
